// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Test from "rescript-test/src/Test.res.js";
import * as SuccessIfOnlyTestPasses from "../src/SuccessIfOnlyTestPasses.res.js";

function stringEqual(message, a, b) {
  Test.assertion(message, "stringEqual", (a, b) => a === b, a, b);
}

Test.test("Say Hi!", () => stringEqual("Say Hi!", SuccessIfOnlyTestPasses.hello(), "Hello, World!"));

export {
  stringEqual,
}
/*  Not a pure module */
